# Configuration file
site_name: CultivaLab Documentation
theme:
  name: material
  logo: assets/CultivaLabLogo3.png
  palette:
    - scheme: slate
      primary: black
      accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
  - mermaid2

nav:
  - Home: index.md
  - Getting Star

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details
  - pymdownx.tabbed
  - tables