# Configuration file
site_name: CultivaLab Documentation
theme:
  name: material
  logo: assets/CultivaLabLogo3.png
  palette:
    - scheme: slate
      primary: black
      accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true

nav:
  - Origen: index.md
  - Introduzcámonos: getting-started.md 
  - Arquitectura del Sistema: architecture.md
  - Modelos de Datos: models-overview.md
  - Capa de Servicios: services-overview.md
  - Capa de Persistencia: storage.md
  - Excepciones: exceptions.md
  - Pruebas: tests.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - attr_list
  - md_in_html